import type { Metadata } from 'next'
import { Inter, Lexend_Deca } from 'next/font/google'
import './globals.css'
import clsxm from '../lib/clsxm'
import { Toaster } from '@/components/ui/toaster'
import { getServerSession } from 'next-auth'
import Provider from '@/providers/SessionProvider'

const inter = Inter({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

const lexend = Lexend_Deca({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend-deca',
})

export const metadata: Metadata = {
  title: 'ADS FE Test',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  return (
    <html lang="en" className={clsxm(lexend.variable, inter.variable)}>
      <body>
        <Provider session={session}>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
